### ISSUE TITLE
User bid twice and both valid may cause user lost his token ?

### ISSUE THREAD

**Issue by hh3755** [SpankChain/sc_auction#2]
https://github.com/SpankChain/sc_auction/blob/d61b1f821e97757b56fb05feaad72c28fe7d3317/contracts/Auction.sol#L313

Here, the assignment always use the most newly token value.But if the user bid twice and both valid,Then It will always use the newest one.

**Comment by ameensol** [comment]
Only one bid per buyer will be accepted. 

https://github.com/SpankChain/sc_auction/blob/d61b1f821e97757b56fb05feaad72c28fe7d3317/contracts/Auction.sol#L311

^ this prevents two bids from the same buyer from being processed, because the `bidWeiAmount` will be set the first time and so the second time it would fail.
